latestnode.settings:
  type: config_object
  label: 'Config for latestnode module'
  mapping:
    typenode:
      type: string
      label: 'Type of nodes'
    countnode:
      type: integer
      label: 'Count of nodes'
